# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download_files', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
