# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_files', '0002_auto_20170410_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(upload_to=b'files'),
        ),
    ]
