# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_files', '0003_auto_20170410_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(upload_to=b'files/'),
        ),
    ]
