# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_files', '0006_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(upload_to=b'user_files/'),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='file',
            field=models.ImageField(upload_to=b'user_files/'),
        ),
    ]
