# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 14:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download_files', '0008_auto_20170517_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=b'')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_files.File')),
            ],
        ),
    ]
