# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download_files', '0009_textview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextView',
            new_name='TextModel',
        ),
    ]
